baseURL = "https://satoru.dev/"
title = "Continuous Kaizen"
copyright = "Copyright &copy; 2019 - satoru"

theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[author]
    name = "satoru"
    github = "suzaku"

[outputs]
home = [ "HTML", "RSS" ]
