baseURL = "https://satoru.dev/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Writing as a way to learn"
theme = "kiera"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


[outputs]
home = [ "HTML", "RSS" ]
