baseURL = "https://satoru.dev/"
title = "Curiousity Driven Development"
copyright = "Copyright &copy; 2020 - satoru"

googleAnalytics = "UA-60059951-1"

theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

disqusShortname = "satorulogic"

[author]
name = "satoru"
github = "suzaku"
twitter = "satorulogic"

[Permalinks]
posts = "/:year/:month/:title/"

[outputs]
home = [ "HTML", "RSS" ]
